apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ZJqNeKONIl1kWKO8VTwMjOLZZICWF+SYyC3F/PAIkEKryNhP+RpfBA==,iv:lKc37+9W9nhkzzE6Ibxo7eqZAtDi9FUd6duGWcnAstY=,tag:cXEKfIbohdIs/ELg2XACvA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lj04tl9hp3zx73f8qgu0cufaq9cllp8c0hepwd8pkgaxf7764ewqmkj5re
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoODZwQnJvdng4aHNiYm1P
            Y2ZsWDhncFdGbDBqRVRmZlBqMGcwcVo0OWdNCnVDUzFEOHZjWDZ2TjZ4ZmdzN1pa
            dlpmMUlxRXA1R3NPQy9XQWxtbHhGSncKLS0tIHFKZEFNN2k2VS80dGxCYjFLN3ln
            Vm0rMitkS1hRUWx3YnhSTjQ4MU5sQVkKVd8Xq/AIAOHdiEHaB7Z567H+dV9Fw8fz
            aUnvu67IwNXPE5m5qlUqmi6FE3/I66VfUMb7cTWCH996xUJfrvKi0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-17T18:28:23Z"
    mac: ENC[AES256_GCM,data:f34XjZkTyn95WiicjzbFmJQjeQ0bJUhSb+9pWB5/EmEenohZ9290OPRi2xqj5s0b06dTjdIS0AvaXFKtlwOavRucgh1p6h7z16BrQDJBebagvKW53fbDjSIiWVXTD/e2wS1SQxI2X6BUP4pVPRZ2b+NPIgCsgSHLGv+bjTc79RY=,iv:PLmnGqCmzge8T6TUlk6W4j+vviPJWZ7MNd2s4TxnT8E=,tag:LIU4F5/oJDW+sRt70dujow==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
