apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:95uQrEWOcNC/X+i4kuzS/irRyI/0ohGbJLOc+7t2Vv0h8Xe9hIO3Y5lC9Y9hGsC8EjPAQWCaXx9uHWJPnJrzZPGBs07Hs3N9RdVYKePIgDBHPnspg9CozkGrq7rlX2fdh07opQKjaq8ypu2/nmGzC6ND9k7zJcQWhef0rfSv5mc1nr+SSYSqOun0vFySB4JWrUbzDN2NNK3rluvEP2YFoYHml77De1/e4aR9bLi1PIDUHQ2aiZsj6ZTn5CoDDWgiYIDgL57TSTkUKRIwCHsQWVSIN9xWRKs4Y6o5OPBt6jS+C+X2DtpAXr02NaDFUl5oHVBEizgnso46wHxRuO9VzO0fcPZo7MDRoiCR2V4eSykVgoWU5qeVdfMr1FCh5SGo,iv:umc9AWYw0OK1c/pdrK/i0pCZTe5eNQmFsiNizezw5/E=,tag:ba73qccySrkqSytR2pAjvQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Ft1b15nJXl6rCKOajnrCeSudAmfVpTtH7PjA45lapcFG8g2FwRwJo/PusJWlvtq1nay5UhrcdKMexenMitjStY2+wkEGbFhJosbSE8YOPL0Tzou6mqk7XWU38eXhHqYv4uwvDfmlFlMDsEO6dqFVdaHUkel2ifoY1+HKMGb1SnMAUxfNoCMdP3UJt4bMc4JsGDhathnMpv1jdw0rJ4qu5ieRj1etqam5PmX4NK1DyjjvsEnbZKlercIUglT5QdiJwRXxGGDcdIBdwoAZug==,iv:I7AEnf1KlN9TQYYSYY0wSUUawqRfwbzqto4A20X6qas=,tag:ipPBtiFZcKu5RRcdrk2wOA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZDJdyp1G/TjtzuNoVOYGdi5zQawWdPTLaNplJ0PbWC3rpVce1yggeGN3aOtpHByraI8VKlPBO+Xyie5FIvUBoQN9bdAlbhtvIbTrG+KPrP7DK0bMqOspaUXNr4dPhna/EiI/nJPgiD67Rj3grar4fXUyzuLkcaXOAIC+uYzPKz21PxnxYXqhEQ2hxXrIePgpP0YLhyGm48l2C3nFVvxcTBwrd6P8hbx76miE,iv:cQhPPxjW00vosmiWGvgTfYaT4+8sdgkwkzL5pZBPk1Q=,tag:hFfOnCCSFe7Fwy6GoIcxAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1lj04tl9hp3zx73f8qgu0cufaq9cllp8c0hepwd8pkgaxf7764ewqmkj5re
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTjI5S0JzVjgwVGVpWGhE
            VFBnL3h3SVZvZitsM2tKVStxUktwZ0RCd2t3CmZRYkVlNk5nT2V1cW5pR1FwVUZi
            MWQ4aWRMWWlCUGJhSEFZcytxRjB3RjgKLS0tIE1aSEZRNmRyVWMwL3FORnpxTmkx
            cER6aXZlc0R0bGY1YkJzZ0ZPOC80a2MK5y6yOebCJHimvLH5BLYIRgYvFQPu+M4Q
            I4yB7Gr5scBxPABxtTP6MzrMK5g0SZYAI4cTm02oMYqs8HGfq4pvxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-10T03:55:58Z"
    mac: ENC[AES256_GCM,data:zrl6zMUM1LY4mWym4yAz40BebhSSs+mGMIbzZJCJgD0XFKeLfa3vUyWjPkFyhIBrkWwzUt4Q6XUcKTDS/ejFHXjJZY6+cuj/lvuOHpmiAuM7VHvNerCJLVf1eWzOu0kTspHWTTbyi5m3q/mQfxDzZc7lFZ0WeuceBClEojONAaA=,iv:F5WlyYCaKzf/eJLyT6zWAAcKOplrblOpw+ITKscx5jI=,tag:XbyrRRkvdKTnCBrM1t3LHQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
