apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: volsync
    namespace: volsync
spec:
    interval: 15m
    chart:
        spec:
            chart: volsync
            version: 1.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: volsync
    values:
        TZ: America/Chicago
        addons:
            codeserver:
                enabled: false
            netshoot:
                enabled: false
            vpn:
                type: disabled
        manageCRDs: true
        manageVSCCRD: true
        metrics:
            main:
                enabled: false
                endpoints:
                    - path: /metrics
                      port: metrics
                targetSelector: metrics
                type: servicemonitor
        podOptions:
            automountServiceAccountToken: true
        proxyImage:
            pullPolicy: IfNotPresent
            repository: quay.io/brancz/kube-rbac-proxy
            tag: v0.14.4@sha256:40d0d5d0032f9bd689bb6ee7d1960048c295e019b7110d5fadea5aff9599baa5
        rbac:
            cluster:
                allServiceAccounts: true
                clusterWide: true
                enabled: true
                primary: false
                rules:
                    - apiGroups:
                        - authentication.k8s.io
                      resources:
                        - tokenreviews
                      verbs:
                        - create
                    - apiGroups:
                        - authorization.k8s.io
                      resources:
                        - subjectaccessreviews
                      verbs:
                        - create
                    - apiGroups:
                        - apps
                      resources:
                        - deployments
                      verbs:
                        - create
                        - delete
                        - deletecollection
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - batch
                      resources:
                        - jobs
                      verbs:
                        - create
                        - delete
                        - deletecollection
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - configmaps
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - events
                      verbs:
                        - create
                        - patch
                        - update
                    - apiGroups:
                        - ""
                      resources:
                        - namespaces
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - nodes
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - persistentvolumeclaims
                      verbs:
                        - create
                        - delete
                        - deletecollection
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - persistentvolumeclaims/finalizers
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - persistentvolumes
                      verbs:
                        - get
                        - list
                        - patch
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - pods
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - pods/log
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - secrets
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - serviceaccounts
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - ""
                      resources:
                        - services
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - events.k8s.io
                      resources:
                        - events
                      verbs:
                        - create
                        - patch
                        - update
                    - apiGroups:
                        - populator.storage.k8s.io
                      resources:
                        - volumepopulators
                      verbs:
                        - create
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - rbac.authorization.k8s.io
                      resources:
                        - rolebindings
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - rbac.authorization.k8s.io
                      resources:
                        - roles
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - security.openshift.io
                      resources:
                        - securitycontextconstraints
                      verbs:
                        - create
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - security.openshift.io
                      resourceNames:
                        - volsync-privileged-mover
                      resources:
                        - securitycontextconstraints
                      verbs:
                        - use
                    - apiGroups:
                        - snapshot.storage.k8s.io
                      resources:
                        - volumesnapshots
                      verbs:
                        - create
                        - delete
                        - deletecollection
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - storage.k8s.io
                      resources:
                        - storageclasses
                      verbs:
                        - get
                        - list
                        - watch
                    - apiGroups:
                        - volsync.backube
                      resources:
                        - replicationdestinations
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - volsync.backube
                      resources:
                        - replicationdestinations/finalizers
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - volsync.backube
                      resources:
                        - replicationdestinations/status
                      verbs:
                        - get
                        - patch
                        - update
                    - apiGroups:
                        - volsync.backube
                      resources:
                        - replicationsources
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - volsync.backube
                      resources:
                        - replicationsources/finalizers
                      verbs:
                        - create
                        - delete
                        - get
                        - list
                        - patch
                        - update
                        - watch
                    - apiGroups:
                        - volsync.backube
                      resources:
                        - replicationsources/status
                      verbs:
                        - get
                        - patch
                        - update
            main:
                clusterWide: false
                enabled: true
                primary: true
                rules:
                    - apiGroups:
                        - ""
                      resources:
                        - configmaps
                      verbs:
                        - get
                        - list
                        - watch
                        - create
                        - update
                        - patch
                        - delete
                    - apiGroups:
                        - coordination.k8s.io
                      resources:
                        - leases
                      verbs:
                        - get
                        - list
                        - watch
                        - create
                        - update
                        - patch
                        - delete
                    - apiGroups:
                        - ""
                      resources:
                        - events
                      verbs:
                        - create
                        - patch
        release_name: volsync
        resources: {}
        securityContext:
            container:
                UMASK: "0022"
                runAsGroup: 568
                runAsUser: 568
            pod:
                fsGroupChangePolicy: OnRootMismatch
        service:
            main:
                ports:
                    main:
                        port: 8081
                        protocol: http
                        targetPort: 8081
            metrics:
                enabled: true
                ports:
                    metrics:
                        enabled: true
                        port: 8443
                        protocol: https
                        targetPort: 8443
                type: ClusterIP
        serviceAccount:
            main:
                enabled: true
                primary: true
        workload:
            main:
                podSpec:
                    containers:
                        kube-rbac-proxy:
                            args:
                                - --secure-listen-address=0.0.0.0:8443
                                - --upstream=http://127.0.0.1:8080/
                                - --logtostderr=true
                                - --tls-min-version=VersionTLS12
                                - --v=0
                            enabled: true
                            imageSelector: proxyImage
                            probes:
                                liveness:
                                    port: 8443
                                    type: tcp
                                readiness:
                                    port: 8443
                                    type: tcp
                                startup:
                                    port: 8443
                                    type: tcp
                            resources:
                                limits:
                                    cpu: 500m
                                    memory: 128Mi
                        main:
                            args:
                                - --health-probe-bind-address=:8081
                                - --metrics-bind-address=127.0.0.1:8080
                                - --leader-elect
                                - --rclone-container-image={{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
                                - --restic-container-image={{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
                                - --rsync-container-image={{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
                                - --rsync-tls-container-image={{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
                                - --syncthing-container-image={{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
                                - --scc-name=volsync-privileged-mover
                            command:
                                - /manager
                            probes:
                                liveness:
                                    path: /healthz
                                readiness:
                                    path: /readyz
                                startup:
                                    path: /readyz
                replicas: 1
                strategy: RollingUpdate
                type: Deployment
